[package]
name = "js-rust-websocket"
version = "0.1.0"
authors = ["fluencelabs"]
edition = "2018"

[dependencies]
async-tungstenite = "0.3.1"
futures = "0.3"

[dependencies.tungstenite]
version = "0.9.2"
default-features = false

[dependencies.async-std]
version = "1.0.0"
features = ["attributes"]